export * from './createYokIcon'
export * from './iconPaths'
export * from './YokIcon'

import { createYokIcon } from './createYokIcon'
import { yokIconPaths, type YokIconName } from './iconPaths'

function createRegistryIcon(name: YokIconName) {
  const icon = yokIconPaths[name]

  return createYokIcon(name, icon.paths, {
    viewBox: icon.viewBox
  })
}

export const YCheckIcon = createRegistryIcon('check')
export const YCloseIcon = createRegistryIcon('close')
export const YPlusIcon = createRegistryIcon('plus')
export const YMinusIcon = createRegistryIcon('minus')
export const YSearchIcon = createRegistryIcon('search')
export const YSettingsIcon = createRegistryIcon('settings')
export const YUserIcon = createRegistryIcon('user')
export const YUsersIcon = createRegistryIcon('users')
export const YLockIcon = createRegistryIcon('lock')
export const YUnlockIcon = createRegistryIcon('unlock')
export const YShieldIcon = createRegistryIcon('shield')
export const YBellIcon = createRegistryIcon('bell')
export const YHomeIcon = createRegistryIcon('home')
export const YMailIcon = createRegistryIcon('mail')
export const YPhoneIcon = createRegistryIcon('phone')
export const YMapPinIcon = createRegistryIcon('mapPin')
export const YGlobeIcon = createRegistryIcon('globe')
export const YMenuIcon = createRegistryIcon('menu')
export const YMoreHorizontalIcon = createRegistryIcon('moreHorizontal')
export const YMoreVerticalIcon = createRegistryIcon('moreVertical')
export const YRefreshIcon = createRegistryIcon('refresh')
export const YLoadingIcon = createRegistryIcon('loading')
export const YInfoIcon = createRegistryIcon('info')
export const YWarningIcon = createRegistryIcon('warning')
export const YHelpIcon = createRegistryIcon('help')
export const YStarIcon = createRegistryIcon('star')
export const YHeartIcon = createRegistryIcon('heart')
export const YEyeIcon = createRegistryIcon('eye')
export const YEyeOffIcon = createRegistryIcon('eyeOff')
export const YFilterIcon = createRegistryIcon('filter')
export const YCopyIcon = createRegistryIcon('copy')
export const YEditIcon = createRegistryIcon('edit')
export const YTrashIcon = createRegistryIcon('trash')
export const YShareIcon = createRegistryIcon('share')
export const YSaveIcon = createRegistryIcon('save')
export const YPrintIcon = createRegistryIcon('print')
export const YUndoIcon = createRegistryIcon('undo')
export const YRedoIcon = createRegistryIcon('redo')
export const YSortAscIcon = createRegistryIcon('sortAsc')
export const YSortDescIcon = createRegistryIcon('sortDesc')
export const YDragIcon = createRegistryIcon('drag')
export const YMaximizeIcon = createRegistryIcon('maximize')
export const YMinimizeIcon = createRegistryIcon('minimize')
export const YChevronDownIcon = createRegistryIcon('chevronDown')
export const YChevronUpIcon = createRegistryIcon('chevronUp')
export const YChevronLeftIcon = createRegistryIcon('chevronLeft')
export const YChevronRightIcon = createRegistryIcon('chevronRight')
export const YArrowUpIcon = createRegistryIcon('arrowUp')
export const YArrowDownIcon = createRegistryIcon('arrowDown')
export const YArrowLeftIcon = createRegistryIcon('arrowLeft')
export const YArrowRightIcon = createRegistryIcon('arrowRight')
export const YExternalLinkIcon = createRegistryIcon('externalLink')
export const YUploadIcon = createRegistryIcon('upload')
export const YDownloadIcon = createRegistryIcon('download')
export const YLoginIcon = createRegistryIcon('login')
export const YLogoutIcon = createRegistryIcon('logout')
export const YInputIcon = createRegistryIcon('input')
export const YTextareaIcon = createRegistryIcon('textarea')
export const YCheckboxIcon = createRegistryIcon('checkbox')
export const YRadioIcon = createRegistryIcon('radio')
export const YSwitchIcon = createRegistryIcon('switch')
export const YCalendarIcon = createRegistryIcon('calendar')
export const YCalendarCheckIcon = createRegistryIcon('calendarCheck')
export const YCalendarClockIcon = createRegistryIcon('calendarClock')
export const YClockIcon = createRegistryIcon('clock')
export const YCalculatorIcon = createRegistryIcon('calculator')
export const YFormIcon = createRegistryIcon('form')
export const YSliderIcon = createRegistryIcon('slider')
export const YSelectIcon = createRegistryIcon('select')
export const YTagIcon = createRegistryIcon('tag')
export const YSuccessIcon = createRegistryIcon('success')
export const YErrorIcon = createRegistryIcon('error')
export const YNoticeIcon = createRegistryIcon('notice')
export const YToastIcon = createRegistryIcon('toast')
export const YModalIcon = createRegistryIcon('modal')
export const YTooltipIcon = createRegistryIcon('tooltip')
export const YEmptyIcon = createRegistryIcon('empty')
export const YTableIcon = createRegistryIcon('table')
export const YListIcon = createRegistryIcon('list')
export const YChartBarIcon = createRegistryIcon('chartBar')
export const YChartLineIcon = createRegistryIcon('chartLine')
export const YPieChartIcon = createRegistryIcon('pieChart')
export const YDatabaseIcon = createRegistryIcon('database')
export const YServerIcon = createRegistryIcon('server')
export const YActivityIcon = createRegistryIcon('activity')
export const YCodeIcon = createRegistryIcon('code')
export const YTerminalIcon = createRegistryIcon('terminal')
export const YCpuIcon = createRegistryIcon('cpu')
export const YCloudIcon = createRegistryIcon('cloud')
export const YFolderIcon = createRegistryIcon('folder')
export const YFileIcon = createRegistryIcon('file')
export const YFileTextIcon = createRegistryIcon('fileText')
export const YFileCodeIcon = createRegistryIcon('fileCode')
export const YImageIcon = createRegistryIcon('image')
export const YArchiveIcon = createRegistryIcon('archive')
export const YClipboardIcon = createRegistryIcon('clipboard')
export const YLinkIcon = createRegistryIcon('link')
export const YBookmarkIcon = createRegistryIcon('bookmark')
export const YPlayIcon = createRegistryIcon('play')
export const YPauseIcon = createRegistryIcon('pause')
export const YStopIcon = createRegistryIcon('stop')
export const YVolumeIcon = createRegistryIcon('volume')
export const YMuteIcon = createRegistryIcon('mute')
export const YCameraIcon = createRegistryIcon('camera')
export const YMicIcon = createRegistryIcon('mic')
export const YLayoutIcon = createRegistryIcon('layout')
export const YSidebarIcon = createRegistryIcon('sidebar')
export const YGridIcon = createRegistryIcon('grid')
export const YColumnsIcon = createRegistryIcon('columns')
export const YRowsIcon = createRegistryIcon('rows')
export const YCardIcon = createRegistryIcon('card')
export const YPanelIcon = createRegistryIcon('panel')
export const YDashboardIcon = createRegistryIcon('dashboard')
export const YKanbanIcon = createRegistryIcon('kanban')
export const YLayersIcon = createRegistryIcon('layers')
export const YPackageIcon = createRegistryIcon('package')
export const YCartIcon = createRegistryIcon('cart')
export const YCreditCardIcon = createRegistryIcon('creditCard')
export const YGiftIcon = createRegistryIcon('gift')
export const YWalletIcon = createRegistryIcon('wallet')
export const YReceiptIcon = createRegistryIcon('receipt')
export const YTruckIcon = createRegistryIcon('truck')
export const YBriefcaseIcon = createRegistryIcon('briefcase')
export const YBuildingIcon = createRegistryIcon('building')
export const YTargetIcon = createRegistryIcon('target')
export const YPaletteIcon = createRegistryIcon('palette')
export const YRocketIcon = createRegistryIcon('rocket')
export const YLogoMarkIcon = createRegistryIcon('logoMark')
export const YSparkleIcon = createRegistryIcon('sparkle')
export const YMintIcon = createRegistryIcon('mint')
export const YCandyIcon = createRegistryIcon('candy')
